# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tyler Beason
tagline:             'PhD Student'
description:         'Personal website of Tyler Beason.'
url:                 http://tbeason.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tyler Beason
  url:               http://tbeason.com
  email:             tbeas12@gmail.com

# Custom vars
version:             0.0.1
